import Head from 'next/head'
import client from '../src/graphql/config';
import LINKS from '../src/graphql/queries';
import styles from '../src/styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        em processo....
      </main>
    </div>
  )
}
