import Head from 'next/head'
import styles from '../src/styles/Links.module.scss'
import profileImage from '../src/images/me.png';
import boxImage from '../src/images/box.svg';
import arrowImage from '../src/images/arrow.svg';
import LINKS from '../src/graphql/queries.js';
import Image from 'next/image';
import client from '../src/graphql/config';

function Links({ links }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainLinks}>
      <header className={styles.headerLinks}>
        <Image src={profileImage} className='profileImage' alt='Giovanna Moeller' width={200} height={200}/>
        <div className={styles.nameBox}>
          <div className={styles.boxImage}>
            <Image src={boxImage} alt='Box' className={styles.box}/>
            <Image src={arrowImage} alt='Arrow' className={styles.arrowImage}/>
          </div>
          <h1>
            Giovanna Moeller
          </h1>
        </div>
        <span>Software Engineer and Content Creator.</span>
      </header>
      <section className={styles.links}>
        {links.map(link => {
          return (
            <a href={link.url} target='_blank' className={styles.link} key={link.name} rel='noreferrer'>
              <span>{link.name}</span>
              <img src={link.icon.url} alt={link.name}/>
            </a>
          )
        })}
      </section>
    </main>
    </div>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: LINKS
  });

  return {
    props: {
      links: data.allLinks
    },
 };
}

export default Links;