import Head from 'next/head'
import styles from '../../src/styles/Links.module.scss'
import profileImage from '../../src/images/me.png';
import boxImage from '../../src/images/box.svg';
import arrowImage from '../../src/images/arrow.svg';
import LINKS from '../../src/graphql/queries.js';
import Image from 'next/image';
import client from '../../src/graphql/config';
import { categories } from '../../src/lib/category';
import Link from 'next/link';

function Links() {
  return (
	<div className={styles.container}>
	  <Head>
		<title>Girl Coding - Links</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	  </Head>

	  <main className={styles.mainLinks}>
	  <header className={styles.headerLinks}>
		<Image src={profileImage} className='profileImage' alt='Giovanna Moeller' width={260} height={260}/>
		<div className={styles.nameBox}>
		  <div className={styles.boxImage}>
			<Image src={boxImage} alt='Box' className={styles.box}/>
			<div className={styles.arrowImage}>
				<Image src={arrowImage} alt='Arrow'/>
			</div>
		  </div>
		  <h1>
			Giovanna Moeller
		  </h1>
		</div>
		<span>Software Engineer and Content Creator @Girl Coding.</span>
	  </header>

    <section className={styles.links}>
      {categories.map(({ name, slug }) => {
        return (
					<Link href={`/links/${slug}`} className={styles.link} key={name} rel='noreferrer'>
						<span>{name}</span>
					</Link>
        )
      })}
	  </section>

	  {/*<section className={styles.links}>
			{links.map(link => {
				return (
				<a href={link.url} target='_blank' className={styles.link} key={link.name} rel='noreferrer'>
					<span>{link.name}</span>
					<img src={link.icon.url} alt={link.name}/>
				</a>
				)
			})}
		</section>*/}
	</main>
	</div>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
	query: LINKS
  });

  return {
	props: {
	  links: data.allLinks
	},
 };
}

export default Links;